(function () {
    const SUBJECT_ID = "eigo";
    const SUBJECT_NAME = "英語";
    const SUBJECT_ORDER = 4;

    const questions = [
        { "q": "次の赤字部分を英語で答えなさい。[[親愛なる友達]]（_____ came from Hong Kong to see me.）", "a": "A dear friend" },
        { "q": "次の赤字部分を英語で答えなさい。[[ウサギを愛している]]（She really _____ .）", "a": "loves rabbits" },
        { "q": "次の赤字部分を英語で答えなさい。[[白いネコが好きだ]]（I _____ .）", "a": "like white cats" },
        { "q": "次の赤字部分を英語で答えなさい。[[私の大好きな本]]（_____ is The Old Man and the Sea.）", "a": "My favorite book" },
        { "q": "次の赤字部分を英語で答えなさい。[[悲しい話]]（He told me _____ .）", "a": "a sad story" },
        { "q": "次の赤字部分を英語で答えなさい。[[大きな犬を恐れていた]]（The boy _____ .）", "a": "was afraid of big dogs" },
        { "q": "次の赤字部分を英語で答えなさい。[[彼のことばに怒っていた]]（The teacher _____ .）", "a": "was angry about his words" },
        { "q": "次の赤字部分を英語で答えなさい。[[このひどい絵]]（Look at _____ .）", "a": "this terrible picture" },
        { "q": "次の赤字部分を英語で答えなさい。[[お金のことは心配しないで]]（Don't _____ .）", "a": "worry about money" },
        { "q": "次の赤字部分を英語で答えなさい。[[一晩中泣いた]]（The little girl _____ .）", "a": "cried all night" },
        { "q": "次の赤字部分を英語で答えなさい。[[そのスポーツイベントについての映画を作った]]（We _____ the sport event.）", "a": "made a movie about" },
        { "q": "次の赤字部分を英語で答えなさい。[[窓を割った]]（He _____ of my room.）", "a": "broke the window" },
        { "q": "次の赤字部分を英語で答えなさい。[[世界を変えた]]（The little girl _____ .）", "a": "changed the world" },
        { "q": "次の赤字部分を英語で答えなさい。[[その鍵を隠した]]（We _____ in a box.）", "a": "hid the key" },
        { "q": "次の赤字部分を英語で答えなさい。[[そのびんを水で満たした]]（I _____ cold water.）", "a": "filled the bottle with" },
        { "q": "次の赤字部分を英語で答えなさい。[[テーブルをおおった]]（My mother _____ with a white cloth.）", "a": "covered the table" },
        { "q": "次の赤字部分を英語で答えなさい。[[靴を売っている]]（He _____ in Yokohama.）", "a": "sells shoes" },
        { "q": "次の赤字部分を英語で答えなさい。[[話すのをやめて]]（_____ and listen to me.）", "a": "Stop talking" },
        { "q": "次の赤字部分を英語で答えなさい。[[駅へ急いだ方がいい]]（You should _____ to catch the train.）", "a": "hurry to the station" },
        { "q": "次の赤字部分を英語で答えなさい。[[車に注意しなさい]]（_____ when you go out.）", "a": "Be careful of cars" },
        { "q": "次の赤字部分を英語で答えなさい。[[趣味がない]]（My father _____ .）", "a": "has no hobbies" },
        { "q": "次の赤字部分を英語で答えなさい。[[ラジオを聴く]]（My father _____ on his way to work.）", "a": "listens to the radio" },
        { "q": "次の赤字部分を英語で答えなさい。[[外国の人形を集めている]]（His wife _____ .）", "a": "collects foreign dolls" },
        { "q": "次の赤字部分を英語で答えなさい。[[その山に登る]]（We will _____ in August.）", "a": "climb the mountain" },
        { "q": "次の赤字部分を英語で答えなさい。[[花の絵を描いた]]（She _____ of flowers in the garden.）", "a": "painted pictures" },
        { "q": "次の赤字部分を英語で答えなさい。[[ピアノの演奏会]]（I went to _____ with my parents.）", "a": "a piano concert" },
        { "q": "次の赤字部分を英語で答えなさい。[[劇場に行く]]（My parents usually _____ on Sundays.）", "a": "go to the theater" },
        { "q": "次の赤字部分を英語で答えなさい。[[ロシアの芸術]]（We will introduce _____ to Japan.）", "a": "Russian art" },
        { "q": "次の赤字部分を英語で答えなさい。[[テレビドラマ]]（We enjoy watching _____ on Wednesday evenings.）", "a": "a TV drama" },
        { "q": "次の赤字部分を英語で答えなさい。[[私のお気に入りのアニメ]]（This is _____ .）", "a": "my favorite cartoon" },
        { "q": "次の赤字部分を英語で答えなさい。[[前の座席]]（He was sitting in _____ .）", "a": "the front seat" },
        { "q": "次の赤字部分を英語で答えなさい。[[戻ってこなかった]]（He went to Africa and never _____ .）", "a": "came back" },
        { "q": "次の赤字部分を英語で答えなさい。[[500キロ離れている]]（Osaka is about _____ from Tokyo.）", "a": "500 km away" },
        { "q": "次の赤字部分を英語で答えなさい。[[左側に]]（There is a post office _____ of the street.）", "a": "on the left side" },
        { "q": "次の赤字部分を英語で答えなさい。[[屋内へ行く]]（She told us to _____ .）", "a": "go inside" },
        { "q": "次の赤字部分を英語で答えなさい。[[外で遊ぶ]]（He told us to _____ .）", "a": "play outside" },
        { "q": "次の赤字部分を英語で答えなさい。[[山の頂上]]（We stood at _____ at 9 a.m.）", "a": "the top of the mountain" },
        { "q": "次の赤字部分を英語で答えなさい。[[川の底]]（I got this stone from _____ .）", "a": "the bottom of the river" },
        { "q": "次の赤字部分を英語で答えなさい。[[真ん中に]]（She set the dish _____ of the table.）", "a": "in the middle" },
        { "q": "次の赤字部分を英語で答えなさい。[[高い塔]]（_____ stands at the foot of the mountain.）", "a": "The high tower" },
        { "q": "次の赤字部分を英語で答えなさい。[[大きな社会変化]]（They don't like _____ .）", "a": "big social change" },
        { "q": "次の赤字部分を英語で答えなさい。[[調査をした]]（They _____ of this plan.）", "a": "did a survey" },
        { "q": "次の赤字部分を英語で答えなさい。[[ニュースを聞いた]]（I _____ about heavy rain in London.）", "a": "heard the news" },
        { "q": "次の赤字部分を英語で答えなさい。[[社会活動に参加している]]（She _____ to help older people.）", "a": "joins social activities" },
        { "q": "次の赤字部分を英語で答えなさい。[[貧しい人々]]（She is kind to _____ .）", "a": "poor people" },
        { "q": "次の赤字部分を英語で答えなさい。[[金持ちの家]]（She is from _____ .）", "a": "a rich family" },
        { "q": "次の赤字部分を英語で答えなさい。[[このレストランでたばこを吸っては]]（You can't _____ .）", "a": "smoke in this restaurant" },
        { "q": "次の赤字部分を英語で答えなさい。[[騒音の問題に直面していた]]（We _____ all the time.）", "a": "faced noise problems" },
        { "q": "次の赤字部分を英語で答えなさい。[[平和を保っている]]（We _____ with our neighbors.）", "a": "keep peace" },
        { "q": "次の赤字部分を英語で答えなさい。[[日本国籍]]（My son does not have _____ .）", "a": "Japanese nationality" },
        { "q": "次の赤字部分を英語で答えなさい。[[修学旅行に沖縄へ行く]]（We will go to Okinawa _____ .）", "a": "on a school trip" },
        { "q": "次の赤字部分を英語で答えなさい。[[月への旅をする]]（My dream is to _____ .）", "a": "travel to the moon" },
        { "q": "次の赤字部分を英語で答えなさい。[[農場に滞在した]]（We _____ for a month.）", "a": "stayed at a farm" },
        { "q": "次の赤字部分を英語で答えなさい。[[おばを訪問する]]（I am going to _____ in London.）", "a": "visit an aunt" },
        { "q": "次の赤字部分を英語で答えなさい。[[自転車に乗った]]（He _____ from Osaka to Kobe.）", "a": "rode a bike" },
        { "q": "次の赤字部分を英語で答えなさい。[[美しい外国の湖]]（I want to go to see _____ .）", "a": "the beautiful foreign lake" },
        { "q": "次の赤字部分を英語で答えなさい。[[世界中で]]（The writer is famous _____ .）", "a": "around the world" },
        { "q": "次の赤字部分を英語で答えなさい。[[小さい島]]（I can see _____ over there.）", "a": "a small island" },
        { "q": "次の赤字部分を英語で答えなさい。[[大きい宮殿]]（_____ is owned by my grandfather.）", "a": "This big palace" },
        { "q": "次の赤字部分を英語で答えなさい。[[イタリアの文化]]（They are interested in _____ .）", "a": "Italian culture" },
        { "q": "次の赤字部分を英語で答えなさい。[[皿洗いをする]]（I _____ after breakfast.）", "a": "do the dishes" },
        { "q": "次の赤字部分を英語で答えなさい。[[彼のことを笑った]]（Everyone _____ .）", "a": "laughed at him" },
        { "q": "次の赤字部分を英語で答えなさい。[[壁から飛び降りた]]（The boy quickly _____ .）", "a": "jumped off the wall" },
        { "q": "次の赤字部分を英語で答えなさい。[[カードを選んだ]]（He _____ and turned it over.）", "a": "picked a card" },
        { "q": "次の赤字部分を英語で答えなさい。[[仕事を見つける]]（It was very difficult for her to _____ .）", "a": "find work" },
        { "q": "次の赤字部分を英語で答えなさい。[[長い線を引いた]]（He _____ on the floor.）", "a": "drew a long line" },
        { "q": "次の赤字部分を英語で答えなさい。[[窓を開けた]]（I _____ to see the stars.）", "a": "opened the window" },
        { "q": "次の赤字部分を英語で答えなさい。[[同じ話をくり返した]]（He _____ .）", "a": "repeated the same story" },
        { "q": "次の赤字部分を英語で答えなさい。[[午前8時30分に出発する]]（We will _____ tomorrow.）", "a": "start at 8:30 a.m." },
        { "q": "次の赤字部分を英語で答えなさい。[[コップを落とした]]（Susan _____ on the floor.）", "a": "dropped a glass" },
        { "q": "次の赤字部分を英語で答えなさい。[[よい仕事を得た]]（My sister _____ in France.）", "a": "got a good job" },
        { "q": "次の赤字部分を英語で答えなさい。[[鉄道技師]]（The boy became _____ .）", "a": "a train engineer" },
        { "q": "次の赤字部分を英語で答えなさい。[[自動車工場で働いている]]（My cousin _____ .）", "a": "works in a car factory" },
        { "q": "次の赤字部分を英語で答えなさい。[[家を建てている]]（Jeff _____ in Africa.）", "a": "builds houses" },
        { "q": "次の赤字部分を英語で答えなさい。[[その試合の審判]]（My father will be _____ .）", "a": "a judge of the game" },
        { "q": "次の赤字部分を英語で答えなさい。[[私の母の命を救った]]（The doctor _____ .）", "a": "saved my mother's life" },
        { "q": "次の赤字部分を英語で答えなさい。[[事務所を開く]]（They are going to _____ in Fukuoka.）", "a": "open an office" },
        { "q": "次の赤字部分を英語で答えなさい。[[いつもよい仕事をする]]（She _____ a great job.）", "a": "always does" },
        { "q": "次の赤字部分を英語で答えなさい。[[だいたい3時間かかる]]（This study program _____ .）", "a": "usually takes three hours" },
        { "q": "次の赤字部分を英語で答えなさい。[[よく彼に会う]]（I _____ in the café.）", "a": "often see him" },
        { "q": "次の赤字部分を英語で答えなさい。[[悲しく感じた]]（I _____ after I read her letter.）", "a": "felt sad" },
        { "q": "次の赤字部分を英語で答えなさい。[[とても楽しかった]]（We _____ at the party.）", "a": "had great fun" },
        { "q": "次の赤字部分を英語で答えなさい。[[おもしろいラジオ番組]]（I heard _____ .）", "a": "an interesting radio program" },
        { "q": "次の赤字部分を英語で答えなさい。[[アジアに興味がある]]（The students _____ .）", "a": "are interested in Asia" },
        { "q": "次の赤字部分を英語で答えなさい。[[わくわくさせるバスケットボールの試合]]（It was _____ .）", "a": "an exciting basketball game" },
        { "q": "次の赤字部分を英語で答えなさい。[[そのダンスに興奮した]]（Everyone was _____ .）", "a": "excited at the dance" },
        { "q": "次の赤字部分を英語で答えなさい。[[簡単な仕事]]（This will be _____ for you.）", "a": "an easy job" },
        { "q": "次の赤字部分を英語で答えなさい。[[難しい本]]（This was _____ for me.）", "a": "a difficult book" },
        { "q": "次の赤字部分を英語で答えなさい。[[退屈な映画]]（I watched _____ with my friend.）", "a": "a boring movie" },
        { "q": "次の赤字部分を英語で答えなさい。[[彼女を気の毒に思う]]（We _____ .）", "a": "feel sorry for her" },
        { "q": "次の赤字部分を英語で答えなさい。[[私の母についてたずねた]]（She _____ .）", "a": "asked about my mother" },
        { "q": "次の赤字部分を英語で答えなさい。[[簡単な質問]]（This may be _____ for you.）", "a": "an easy question" },
        { "q": "次の赤字部分を英語で答えなさい。[[私に答える]]（No one could _____ .）", "a": "answer me" },
        { "q": "次の赤字部分を英語で答えなさい。[[その物語について私に多くのことを話さなかった]]（She did not _____ .）", "a": "tell me much about the story" },
        { "q": "次の赤字部分を英語で答えなさい。[[「進め」を意味する]]（The green light _____ .）", "a": "means \"Go.\"" },
        { "q": "次の赤字部分を英語で答えなさい。[[就職の面接]]（My brother had _____ with the supermarket.）", "a": "a job interview" },
        { "q": "次の赤字部分を英語で答えなさい。[[理由がある]]（I _____ to do it.）", "a": "have a reason" },
        { "q": "次の赤字部分を英語で答えなさい。[[その問題についてもう一度考えた]]（I _____ again and again.）", "a": "thought about the matter" },
        { "q": "次の赤字部分を英語で答えなさい。[[目標を持っている]]（He _____ of studying two hours a day.）", "a": "has the goal" },
        { "q": "次の赤字部分を英語で答えなさい。[[あなたの考えが本当に気に入っている]]（We really _____ .）", "a": "like your idea" },
        { "q": "次の赤字部分を英語で答えなさい。[[よい趣味]]（Playing the piano is _____ .）", "a": "a good hobby" },
        { "q": "次の赤字部分を英語で答えなさい。[[悪い少年だった]]（I was _____ .）", "a": "a bad boy" },
        { "q": "次の赤字部分を英語で答えなさい。[[重要な会議]]（We will have _____ tomorrow.）", "a": "an important meeting" },
        { "q": "次の赤字部分を英語で答えなさい。[[高価な服]]（His father wears _____ .）", "a": "expensive clothes" },
        { "q": "次の赤字部分を英語で答えなさい。[[本当の金]]（Is this watch made of _____ ?）", "a": "real gold" },
        { "q": "次の赤字部分を英語で答えなさい。[[本当の話]]（She told us _____ .）", "a": "a true story" },
        { "q": "次の赤字部分を英語で答えなさい。[[間違ったニュース]]（How can we stop _____ ?）", "a": "false news" },
        { "q": "次の赤字部分を英語で答えなさい。[[電子メールを書いた]]（I _____ to him.）", "a": "wrote an email" },
        { "q": "次の赤字部分を英語で答えなさい。[[彼の自宅の住所]]（Do you know _____ ?）", "a": "his home address" },
        { "q": "次の赤字部分を英語で答えなさい。[[長い手紙]]（I got _____ from him.）", "a": "a long letter" },
        { "q": "次の赤字部分を英語で答えなさい。[[大きなパーティーを開いた]]（We _____ at our house.）", "a": "had a big party" },
        { "q": "次の赤字部分を英語で答えなさい。[[大きな行事を開催した]]（Our club _____ on Tuesday.）", "a": "held a big event" },
        { "q": "次の赤字部分を英語で答えなさい。[[秋祭り]]（Our town has _____ .）", "a": "an autumn festival" },
        { "q": "次の赤字部分を英語で答えなさい。[[水泳競技会で勝った]]（Mary _____ .）", "a": "won the swimming contest" },
        { "q": "次の赤字部分を英語で答えなさい。[[彼の誕生日を祝った]]（We _____ on Saturday.）", "a": "celebrated his birthday" },
        { "q": "次の赤字部分を英語で答えなさい。[[よい思い出]]（The opera was _____ of this spring.）", "a": "a good memory" },
        { "q": "次の赤字部分を英語で答えなさい。[[楽しいクリスマスを]]（Have _____ !）", "a": "a very merry Christmas" },
        { "q": "次の赤字部分を英語で答えなさい。[[ホテルのお客様]]（This place is for _____ only.）", "a": "hotel guests" },
        { "q": "次の赤字部分を英語で答えなさい。[[重要な役割を果たした]]（Everyone _____ .）", "a": "played an important role" },
        { "q": "次の赤字部分を英語で答えなさい。[[選手の完全な一覧表]]（Can I get _____ ?）", "a": "a full list of players" }
    ];

    window.QUIZ_SUBJECTS = window.QUIZ_SUBJECTS || {};
    window.QUIZ_SUBJECTS[SUBJECT_ID] = {
        id: SUBJECT_ID,
        name: SUBJECT_NAME,
        order: SUBJECT_ORDER,
        questions: questions
    };
})();
